# Generated by Django 4.1 on 2022-09-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlinebuilderapi', '0003_rename_venue_event_venue_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue_id',
            new_name='venue',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='location_id',
            new_name='location',
        ),
    ]
