# Generated by Django 4.1 on 2022-09-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlinebuilderapi', '0004_rename_venue_id_event_venue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='location',
            new_name='location_id',
        ),
    ]
